[project]
name = "frontend"
version = "0.1.0"
dependencies = [
    "chainlit",
    "backend" # Direct dependency on your local backend package
]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"