[project]
name = "therapy-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chainlit>=2.9.4",
    "langchain>=1.2.2",
    "langchain-google-genai>=4.1.3",
]
